server:
  port: 8888
#应用名称
spring:
  application:
    name: api-gateway
  cloud:
    nacos: # nacos 配置
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes: #数组形式
        - id: oreder-service #路由唯一标识
          #uri: http://127.0.0.1:8000 #想要转发的地址
          uri: lb://xdclass-order-service #从nacos进行转发，这里是注册到nacos中的地址，lb：表示负载均衡
          order: 1 #优先级，数字越小优先级越高
          predicates: #断言
            #配置那个路径才转发（意思就是前端请求的前缀是 order-server 这个才转发）
            - Path=/order-server/**
            #配置这个时间后就不能转发了
#            - Before=2022-08-24T01:01:01.000+08:00
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1 #去掉第一层前缀（意思就是在转发过程中去掉 /order-server/ 这一层，因为实际路径是没有这一层的）
      discovery:
        locator:
          enabled: true #开启网关拉起 nacos 的服务
